task_name: short_term_forecast
is_training: 1
model_id: btc_daily
model: CARD

# Data loader section for Bitcoin dataset
data: btc                   # Use 'btc' dataset
root_path: './dataset/btc/'  # Path to your Bitcoin dataset directory
data_path: 'btc_train.csv'   # Specify your Bitcoin train CSV file
test_data_path: 'btc_test.csv' # Specify your Bitcoin test CSV file
features: M                  # Multivariate features (Close, Volume, SMA)
target: Close                # Target feature for prediction (Bitcoin Close prices)
freq: d                      # Daily frequency for time-series data
checkpoints: './checkpoints/' # Directory to save model checkpoints


## Data loader section for M4 Daily
#data: m4                   # Use 'm4' dataset
#root_path: './dataset/m4/'  # Path to the M4 dataset directory
#data_path: 'daily_train.csv' # Specify the M4 daily training dataset
#test_data_path: 'daily_test.csv' # Specify the M4 daily testing dataset
#features: M                 # Multivariate features
#target: OT                  # Target feature for prediction (adjust if necessary)
#freq: d                     # Daily frequency for time-series data
#checkpoints: './checkpoints/' # Directory to save model checkpoints
#
#m4_info: './dataset/m4/m4-info.csv' # Path to the M4 info file (required for M4)
#train_npz: './dataset/m4/training.npz' # Path to M4 training data in .npz format
#test_npz: './dataset/m4/test.npz'      # Path to M4 testing data in .npz format

# forecasting task
seq_len: 96
label_len: 48
pred_len: 20
seasonal_patterns: Daily

# imputation task
mask_rate: 0.25

# anomaly detection task
anomaly_ratio: 0.25

# model define
top_k: 5
num_kernels: 6
enc_in: 3 # Number of input features (1 for m4)
dec_in: 1 # Number of input features (1 for m4)
c_out: 1 # Number of output features (1 for m4)
d_model: 128
n_heads: 16
e_layers: 2
d_layers: 1
d_ff: 512
moving_avg: 25
factor: 3
distil: True  # Set to False to disable distillation
dropout: 0.0
embed: timeF
activation: gelu
output_attention: False

# optimization
num_workers: 10
itr: 1
train_epochs: 10
batch_size: 128
patience: 400
learning_rate: 0.0005
des: Exp
loss: SMAPE
lradj: CARD
use_amp: False

# GPU
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0,1,2,3'

# de-stationary projector params
p_hidden_dims: [128, 128]
p_hidden_layers: 2
alpha: 0.5
beta: 0.5
dp_rank: 8
rescale: 1

fc_dropout: 0.3
head_dropout: 0.3
patch_len: 16
stride: 1
momentum: 0.1

optimizer: adam
local_rank: 0
devices_number: 1
use_statistic: False
use_decomp: False
same_smoothing: False
warmup_epochs: 0
weight_decay: 0
merge_size: 2
use_untoken: 0
pct_start: 0.3

seg_len: 6
win_size: 2
fix_seed: 'None'

# others
use_wandb: False


