# Task settings
task_name: btc_default
is_training: 1 # 0 for Testing only , 1 for training
is_predicting: False # False for training / Testing , True for prediction
model_id: hourly_short_S
model: CARD

#Plotitng settings
pred_file_name: 'daily_short'
show_date: False # Show date on x-axis in visual function
time_print_ticks: 100 # Number of ticks on x-axis in visual function

# Data loader section
data: btc
root_path: './dataset/'
data_path: 'btc_hourly_check.csv'
features: 'S' # 'MS' multi (Price, volume etc') --> single (price) , 's' single --> single , 'M' multi --> multi
target: Price
freq: h
checkpoints: './checkpoints/'

# Forecasting parameters
seq_len: 350
label_len: 40
pred_len: 40

# Model architecture
fc_dropout: 0.05
head_dropout: 0.0
patch_len: 16
stride: 8
padding_patch: 'end'
revin: 1
affine: 0
subtract_last: 0
decomposition: 0
kernel_size: 25
individual: 0

embed_type: 0
enc_in: 1  # Adjust for BTC prediction (Price and Volume)
dec_in: 1
c_out: 1
d_model: 16
n_heads: 8
e_layers: 1
d_layers: 1
d_ff: 32
moving_avg: 25
factor: 1  # Attention factor for scaling
distil: True
dropout: 0.3
embed: 0 # 'timeF'
activation: 'gelu'
output_attention: False

# Optimization settings
num_workers: 10
itr: 1
train_epochs: 10
batch_size: 128 # 16 did the best job for daily data
patience: 3
learning_rate: 0.0001
des: 'BTC Long-Term Forecasting'
loss: 'mse'
lradj: 'CARD'
pct_start: 0.3
use_amp: False

# GPU settings
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0'

# Additional parameters
random_seed: 2021
optimizer: 'adam'
alpha: 0.5
beta: 0.5
dp_rank: 8
rescale: 1
merge_size: 2
momentum: 0.1
local_rank: 0
devices_number: 1
use_statistic: False
use_decomp: False
same_smoothing: False
warmup_epochs: 0
