# Task settings
task_name: long_term_forecast
is_training: 1
model_id: btc_daily_long
model: CARD

# Data loader section for Bitcoin dataset
#data: btc
#root_path: './dataset/btc/'
#data_path: 'btc_train.csv'
#test_data_path: 'btc_test.csv'
#features: ['Price', 'Volume']
#target: Price
#freq: d
#checkpoints: './checkpoints/'
#random_seed: 2021  # Set the same random seed as in the script

# Forecasting parameters
seq_len: 720
label_len: 96  # Adjust based on your prediction goals
pred_len: 96  # Modify for the desired prediction length

# ETT sanity check option (uncomment to run ETT data instead)
root_path: './dataset/'
data_path: 'ETTh1.csv'
data: ETTh1

# Model architecture
enc_in: 2  # Number of input features (Price and Volume)
d_model: 16
n_heads: 2
d_ff: 32
e_layers: 2
dropout: 0.3
fc_dropout: 0.3
head_dropout: 0.0
patch_len: 16
stride: 8

# Optimization settings
train_epochs: 100
patience: 10
batch_size: 128
learning_rate: 0.0001
lradj: CARD
warmup_epochs: 30
itr: 1

# GPU settings
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0'

# Logging settings
log_dir: './logs/LongForecasting/'
des: 'BTC Exp'
use_amp: False
