# ETT sanity check option (uncomment to run ETT data instead)
root_path: './dataset/'
data_path: 'ETTh1.csv'
data: ETTh1
features: M

# Task settings
task_name: long_term_forecast
is_training: 1
model_id: btc_daily_long
model: CARD

## Data loader section
#data: btc
#root_path: './dataset/btc/'
#data_path: 'btc_train.csv'
#test_data_path: 'btc_test.csv'
#features: ['Price', 'Volume']
target: Price
freq: d
checkpoints: './checkpoints/'

# Forecasting parameters
seq_len: 720
label_len: 96
pred_len: 96

# Model architecture
fc_dropout: 0.05
head_dropout: 0.0
patch_len: 16
stride: 8
padding_patch: 'end'
revin: 1
affine: 0
subtract_last: 0
decomposition: 0
kernel_size: 25
individual: 0

embed_type: 0
enc_in: 2  # Adjust for BTC prediction (Price and Volume)
dec_in: 2
c_out: 2
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1  # Attention factor for scaling
distil: True
dropout: 0.05
embed: 'timeF'
activation: 'gelu'
output_attention: False

# Optimization settings
num_workers: 10
itr: 1
train_epochs: 100
batch_size: 128
patience: 100
learning_rate: 0.0001
des: 'BTC Long-Term Forecasting'
loss: 'mse'
lradj: 'type3'
pct_start: 0.3
use_amp: False

# GPU settings
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0'

# Additional parameters
random_seed: 2021
optimizer: 'adam'
alpha: 0.5
beta: 0.5
dp_rank: 8
rescale: 1
merge_size: 2
momentum: 0.1
local_rank: 0
devices_number: 1
use_statistic: False
use_decomp: False
same_smoothing: False
warmup_epochs: 0
